### ISSUE TITLE
Ckeditor not visible?

### ISSUE THREAD

**Issue by kukrik** [qcubed/plugin_ckeditor#2] opened 2015-06-25 12:57 UTC
Something is missing, that does not appear in the text editor. Textarea (only this) come visible and disappear quickly.

@spekary, mastered something to say?

![screen shot 2015-06-25 at 15 43 39](https://cloud.githubusercontent.com/assets/2853034/8354724/d2470992-1b52-11e5-9d7f-518a9950660a.png)

**Comment by spekary** [comment] 2015-06-27 01:36
Check for javascript errors. Probably a path is not correct.

**Comment by kukrik** [comment] 2015-06-28 21:52
Thanks for your suggestion! Here is summary.

I found the reason why the path is not working. The culprit is "qc.baseDir" within file "QCKSetup.js" that do not work correctly.

I had to replace the correct address CKEDITOR_BASEPATH var = qc.baseDir + '/vendor/ckeditor/ ckeditor/ "; Right CKEDITOR_BASEPATH var = "/qcubed_beta-3.0/vendor/ckeditor/ckeditor/".

But in my opinion this is not the correct solution. DOCROOT be taken from configuration.inc.php. But how?

I scan the whole project matches "qc.baseDir" and found that the line from QFormBase.class.php 1735: $ strEndScript = sprintf ('qc.baseDir = "%s"' , **VIRTUAL_DIRECTORY**).

I think this match will not give DOCROOT. Or I'm wrong here?

**Comment by kukrik** [comment] 2015-06-28 22:19
Secondly, I want to ask you, good @spekary!

I know that files put override it if we put in the folder /project/includes/plugins. But how can we configure QCKEditor if it is necessary. To configure /ckeditor/ckeditor/config.js can do. Similarly, if we want to put plugins to the editor... Composer updating everything to lose ?! Or not?

What would be your best ideas or suggestions?

**Comment by spekary** [comment] 2015-06-29 18:23
That is a good question that is on the list to figure out. We need to move the CKEditor.php file out of the vendor directory and  put it somewhere in the project directory. The problem is that the file will be recreated with a composer update and there will be a conflict. The same is true for all plugins. I have to think about this one a bit.

**Comment by spekary** [comment] 2015-06-29 18:31
Try again using the latest beta 3.0 build. There was a problem with basedir. It was not also getting SUB_DIRECTORY. That should be fixed, and should make the QCKSetup work.

**Comment by kukrik** [comment] 2015-06-29 19:07
I tried again. Nothing has changed. I updated when you've got something merged together...

**Comment by spekary** [comment] 2015-06-29 22:17
Issue #711 in the framework should fix this. Please make sure you are getting that change.

**Comment by kukrik** [comment] 2015-06-29 23:13
@spekary, you are right! I do not know why the composer upgrades do not work and do not accept the new changes/improvements against?

Anyway, I spent a lot of time, which was not at all necessary. In fact, your job with CKEditor plugin is fantastic and is working perfectly :+1: .

Very sorry for that, you're wasting a lot of time to me.

Anyway, it would be necessary to think about how to resolve other issues, as I have previously written :)

**Closed as completed** 2016-07-28 17:48 UTC
